{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.0.jar",
          "url": "asm_util-1.3.0.jar",
          "size": 119934,
          "sha512": "042fa02b92801c7355a1c92579918ccb96bf1a05c0b7e7e65e0fb6140173b369e6a7731ab0ea13684607e068b04857f1057753157e803c7049f920d3f73422e1",
          "sha256": "e50447f90cc4b36bd2f7e69c19566a57eec63ba4950e0427f7405af182816897",
          "sha1": "cc03c9a09e4e684338b6b94680fcd9c5a3790dc8",
          "md5": "81af97024760ab05263839aee95b70c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.0.jar",
          "url": "asm_util-1.3.0.jar",
          "size": 119934,
          "sha512": "042fa02b92801c7355a1c92579918ccb96bf1a05c0b7e7e65e0fb6140173b369e6a7731ab0ea13684607e068b04857f1057753157e803c7049f920d3f73422e1",
          "sha256": "e50447f90cc4b36bd2f7e69c19566a57eec63ba4950e0427f7405af182816897",
          "sha1": "cc03c9a09e4e684338b6b94680fcd9c5a3790dc8",
          "md5": "81af97024760ab05263839aee95b70c2"
        }
      ]
    }
  ]
}
