{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.1.3.jar",
          "url": "asm_util-1.1.3.jar",
          "size": 93468,
          "sha512": "e104f311c58715be94442522780a248e976ee230e2aec2ebc4aef990ac0eefc38f0f28ea252eb8549cd41dfcc716bf675afee08fbd7215afbbbda562e99a6060",
          "sha256": "dc6b738d3bbe1a4592496354d6d4ddd1621cd65bfccfd197565333bb0f25680a",
          "sha1": "4e911c8cadcc7adcad87f1bc882e045709ef79dd",
          "md5": "0a8ca18d8c282e71718118fef0620922"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.1.3.jar",
          "url": "asm_util-1.1.3.jar",
          "size": 93468,
          "sha512": "e104f311c58715be94442522780a248e976ee230e2aec2ebc4aef990ac0eefc38f0f28ea252eb8549cd41dfcc716bf675afee08fbd7215afbbbda562e99a6060",
          "sha256": "dc6b738d3bbe1a4592496354d6d4ddd1621cd65bfccfd197565333bb0f25680a",
          "sha1": "4e911c8cadcc7adcad87f1bc882e045709ef79dd",
          "md5": "0a8ca18d8c282e71718118fef0620922"
        }
      ]
    }
  ]
}
