{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "data_util",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.5.jar",
          "url": "data_util-1.3.5.jar",
          "size": 222264,
          "sha512": "fb49bc348642931d781e20e637fbfa9fc4cf1892d3f8872ca3cc22bb854631b3e2cee93d29a0cd367aa7c99859a2ae5507e65e8e878d0c632725c409fb0bf0de",
          "sha256": "e1596aa97e907171cf570305c564125c382f15dd7e23239e0074d352fb34aa69",
          "sha1": "306210a0da7bb08762f93e84d25f957df8d332f1",
          "md5": "0e6170a02771aee56f6e901eb7ab4f93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.5.jar",
          "url": "data_util-1.3.5.jar",
          "size": 222264,
          "sha512": "fb49bc348642931d781e20e637fbfa9fc4cf1892d3f8872ca3cc22bb854631b3e2cee93d29a0cd367aa7c99859a2ae5507e65e8e878d0c632725c409fb0bf0de",
          "sha256": "e1596aa97e907171cf570305c564125c382f15dd7e23239e0074d352fb34aa69",
          "sha1": "306210a0da7bb08762f93e84d25f957df8d332f1",
          "md5": "0e6170a02771aee56f6e901eb7ab4f93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data_util-1.3.5-sources.jar",
          "url": "data_util-1.3.5-sources.jar",
          "size": 27291,
          "sha512": "d31ece584016407a6f0361726d3ccce46130f4a7b498bdb0339a647512a4b156f737e2f821eddad5742ecdadf5a9b4122a432b699830b8ab57ef1ca09fa6a3da",
          "sha256": "81be3705ea06423e4194694f1c169911ab302b748dd692ac2225145216699526",
          "sha1": "24b09c49690c173e3315f970777a114928b0c19f",
          "md5": "2467a7d42a63027b439a868730dac59d"
        }
      ]
    }
  ]
}
