{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.1.2.jar",
          "url": "asm_util-1.1.2.jar",
          "size": 93132,
          "sha512": "f4baddcde877020b708c5ef2f570fb51e1da3adfc19e9758a7f6e0cbb10ac7f7239210e90d10ed06c1bda95c8ecc49ac3ab4fd53c454546349be7b452896479f",
          "sha256": "28208ec02b02080f6a232e50b925e51e9b80450cb19f525a343edac9834c72b6",
          "sha1": "2637ec4d879e1e064c0ebeefd3a0978549ee6e14",
          "md5": "26cf8e5eb0142a9eb34a0797f8457f41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.1.2.jar",
          "url": "asm_util-1.1.2.jar",
          "size": 93132,
          "sha512": "f4baddcde877020b708c5ef2f570fb51e1da3adfc19e9758a7f6e0cbb10ac7f7239210e90d10ed06c1bda95c8ecc49ac3ab4fd53c454546349be7b452896479f",
          "sha256": "28208ec02b02080f6a232e50b925e51e9b80450cb19f525a343edac9834c72b6",
          "sha1": "2637ec4d879e1e064c0ebeefd3a0978549ee6e14",
          "md5": "26cf8e5eb0142a9eb34a0797f8457f41"
        }
      ]
    }
  ]
}
