{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "data_util",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.2.jar",
          "url": "data_util-1.3.2.jar",
          "size": 222277,
          "sha512": "3db630a5834538d66e7aefe4d97d5a15340f4e17a5b8486aa1e967404265030f9ea41793cdc935675186bcad9b67f025b628e252e32e62fc016d802b156ed621",
          "sha256": "e7635597fc1d27034342da510424fa03d67c24bfa37188bbf1d7d7a97663ceb1",
          "sha1": "91c375fd6e1c5af0bbd0c95c22cfc48eacde906f",
          "md5": "92269f9d290e9b8875f5de396a16b639"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.2.jar",
          "url": "data_util-1.3.2.jar",
          "size": 222277,
          "sha512": "3db630a5834538d66e7aefe4d97d5a15340f4e17a5b8486aa1e967404265030f9ea41793cdc935675186bcad9b67f025b628e252e32e62fc016d802b156ed621",
          "sha256": "e7635597fc1d27034342da510424fa03d67c24bfa37188bbf1d7d7a97663ceb1",
          "sha1": "91c375fd6e1c5af0bbd0c95c22cfc48eacde906f",
          "md5": "92269f9d290e9b8875f5de396a16b639"
        }
      ]
    }
  ]
}
