{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.3.jar",
          "url": "asm_util-1.3.3.jar",
          "size": 126234,
          "sha512": "9c1e0cec67156db2fd824cba533db75ad1291dde707edd827add4743a10c7bbdd6f9298105e9843cc7023150f505532eb75eb31409ba01075119453c47e56769",
          "sha256": "e5b68ccf3e99a800f62c0ef5b02b9114c821a8e6674a90cdf8564b93ea310001",
          "sha1": "163c0ba72a7d8ae33ab4e676eec3241d05b98eae",
          "md5": "6a87a5ff611dacd2474ba541b99d9329"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.3.jar",
          "url": "asm_util-1.3.3.jar",
          "size": 126234,
          "sha512": "9c1e0cec67156db2fd824cba533db75ad1291dde707edd827add4743a10c7bbdd6f9298105e9843cc7023150f505532eb75eb31409ba01075119453c47e56769",
          "sha256": "e5b68ccf3e99a800f62c0ef5b02b9114c821a8e6674a90cdf8564b93ea310001",
          "sha1": "163c0ba72a7d8ae33ab4e676eec3241d05b98eae",
          "md5": "6a87a5ff611dacd2474ba541b99d9329"
        }
      ]
    }
  ]
}
