{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "data_util",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.2.7.jar",
          "url": "data_util-1.2.7.jar",
          "size": 197469,
          "sha512": "a8ea1a710453d799c0013ccaa280be3c95aeea2ab31529bee877177d79c401bcbbea16b855764086e41722738be8ae213a63c10238586a9c78698e54fcb6631c",
          "sha256": "68e9768bfb8e64a1f8eb9b0dc738284abd6b3924ee046220b81c6b22c2f37747",
          "sha1": "d7f67a5fcbe55f7d90bd9c88c3cc26fe91de6c76",
          "md5": "0ed4d9842b3b9660fde41c1f13e6a80e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.2.7.jar",
          "url": "data_util-1.2.7.jar",
          "size": 197469,
          "sha512": "a8ea1a710453d799c0013ccaa280be3c95aeea2ab31529bee877177d79c401bcbbea16b855764086e41722738be8ae213a63c10238586a9c78698e54fcb6631c",
          "sha256": "68e9768bfb8e64a1f8eb9b0dc738284abd6b3924ee046220b81c6b22c2f37747",
          "sha1": "d7f67a5fcbe55f7d90bd9c88c3cc26fe91de6c76",
          "md5": "0ed4d9842b3b9660fde41c1f13e6a80e"
        }
      ]
    }
  ]
}
