{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "data_util",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.0.jar",
          "url": "data_util-1.3.0.jar",
          "size": 206948,
          "sha512": "03efa7cd1d18fdf9589d5a3d2b2fd000f5e5849850dd3cdbc50fdb42de2d8cf0d9f5bfb6d812da38e209f0c91306d1b9d6c733e2399d5a4f216ea682ff210d69",
          "sha256": "23f72b2234121df4b4de00ba6e31478709d30d4673b01d44122a11f0f3054869",
          "sha1": "adc4388d6c090743f4a776a752ece15673fec6f9",
          "md5": "17e898ea13d03fd83bbd28f049d6f28a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.0.jar",
          "url": "data_util-1.3.0.jar",
          "size": 206948,
          "sha512": "03efa7cd1d18fdf9589d5a3d2b2fd000f5e5849850dd3cdbc50fdb42de2d8cf0d9f5bfb6d812da38e209f0c91306d1b9d6c733e2399d5a4f216ea682ff210d69",
          "sha256": "23f72b2234121df4b4de00ba6e31478709d30d4673b01d44122a11f0f3054869",
          "sha1": "adc4388d6c090743f4a776a752ece15673fec6f9",
          "md5": "17e898ea13d03fd83bbd28f049d6f28a"
        }
      ]
    }
  ]
}
