{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "big_shot.common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "big_shot.common-1.0.0.jar",
          "url": "big_shot.common-1.0.0.jar",
          "size": 85738,
          "sha512": "f8e3db96e213f1f3105e7f3d39970eff968fd104896de27b322ea336708a2edee5150dd7196400f3cfcf8bffee93aa70bc8f0d24249b17d04775c902f1f3b289",
          "sha256": "90c09cdc52264ac3a78e63c2d5dbbdae6e9ce2f76f68fd961c3c62d27dff7141",
          "sha1": "8613076f805a8d22d17401bb06067f8b0885ad11",
          "md5": "cb58ee8cad1fe543525dbdcf8fc2e931"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.typho",
          "module": "asm_util",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "net.typho",
          "module": "data_util",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "big_shot.common-1.0.0.jar",
          "url": "big_shot.common-1.0.0.jar",
          "size": 85738,
          "sha512": "f8e3db96e213f1f3105e7f3d39970eff968fd104896de27b322ea336708a2edee5150dd7196400f3cfcf8bffee93aa70bc8f0d24249b17d04775c902f1f3b289",
          "sha256": "90c09cdc52264ac3a78e63c2d5dbbdae6e9ce2f76f68fd961c3c62d27dff7141",
          "sha1": "8613076f805a8d22d17401bb06067f8b0885ad11",
          "md5": "cb58ee8cad1fe543525dbdcf8fc2e931"
        }
      ]
    }
  ]
}
