{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.4.jar",
          "url": "asm_util-1.3.4.jar",
          "size": 128032,
          "sha512": "932f502aaec18585f70d81ee4bf60ddf2f88a96ca19bc5ed35fcaa0a6d5e495527eaf3d45167e545398806b22f7e4acd31bb1e85ff0b5eb2c0c7f146357031c8",
          "sha256": "a2de80963830279c98e410d1356a845f0f013cfb58be323c34decd6b7f06aea0",
          "sha1": "5e366b3b14802143e56a5a97af49b7153e994750",
          "md5": "e8d38ca092c918962d6050a13d854dc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.4.jar",
          "url": "asm_util-1.3.4.jar",
          "size": 128032,
          "sha512": "932f502aaec18585f70d81ee4bf60ddf2f88a96ca19bc5ed35fcaa0a6d5e495527eaf3d45167e545398806b22f7e4acd31bb1e85ff0b5eb2c0c7f146357031c8",
          "sha256": "a2de80963830279c98e410d1356a845f0f013cfb58be323c34decd6b7f06aea0",
          "sha1": "5e366b3b14802143e56a5a97af49b7153e994750",
          "md5": "e8d38ca092c918962d6050a13d854dc0"
        }
      ]
    }
  ]
}
