{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "crucible.ide_data",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crucible.ide_data-1.0.0.jar",
          "url": "crucible.ide_data-1.0.0.jar",
          "size": 17324,
          "sha512": "cec2f4ee877d3cc77a8e174ab2741f1abc9c79cbad01823866325e75e749e42448fa8a41b5f84fbbe150e9e15dc067ec6ee753eb7bb15ccf15ea58fa9ded71ef",
          "sha256": "d630f0901c285dc56f9ff9ab1b5a6f0dd9273012853191825b436f90ba797228",
          "sha1": "04bc4b1de7392cd813be7e632857cc78226e9d4d",
          "md5": "0a24637f5bca15e0cbb400fb0f3b7799"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.typho",
          "module": "data_util",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crucible.ide_data-1.0.0.jar",
          "url": "crucible.ide_data-1.0.0.jar",
          "size": 17324,
          "sha512": "cec2f4ee877d3cc77a8e174ab2741f1abc9c79cbad01823866325e75e749e42448fa8a41b5f84fbbe150e9e15dc067ec6ee753eb7bb15ccf15ea58fa9ded71ef",
          "sha256": "d630f0901c285dc56f9ff9ab1b5a6f0dd9273012853191825b436f90ba797228",
          "sha1": "04bc4b1de7392cd813be7e632857cc78226e9d4d",
          "md5": "0a24637f5bca15e0cbb400fb0f3b7799"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crucible.ide_data-1.0.0-sources.jar",
          "url": "crucible.ide_data-1.0.0-sources.jar",
          "size": 1883,
          "sha512": "ffcb0f7b7a47858baab9d9b649efcf13281da1454b2ce44654459416ef104ff1766fa2081568c6d58739f506704257ba365c6afaa62356566dd75a0d8d59ad91",
          "sha256": "46ed9de2ede7a90e89802aaf330e8e18ce01894921d7dfb3d683f9552c945579",
          "sha1": "493384a9a0c362b7c510627c20860e54d1bb8c86",
          "md5": "5988a58d2f5dd9dd2ee4cd6ee06a1c61"
        }
      ]
    }
  ]
}
