{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "crucible.ide_data",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crucible.ide_data-1.1.1.jar",
          "url": "crucible.ide_data-1.1.1.jar",
          "size": 20170,
          "sha512": "1cf6386e61a4edd970459e7604a63306735a91463b2dcb4b656347715dbf77850ba3bbfa53c0575cb3b21e02deaedce8f36bae4e2be689a5164081b0c8575b0e",
          "sha256": "fb77516145837f40cbc038be30f450b694ca468bf6453a8558fa5a33f423ad57",
          "sha1": "eebee5822cc48eece5f9a807a5f04bf0003ca429",
          "md5": "52cbc0af9795454b6be74b6848d36af7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.typho",
          "module": "data_util",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm-host"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm-host",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crucible.ide_data-1.1.1.jar",
          "url": "crucible.ide_data-1.1.1.jar",
          "size": 20170,
          "sha512": "1cf6386e61a4edd970459e7604a63306735a91463b2dcb4b656347715dbf77850ba3bbfa53c0575cb3b21e02deaedce8f36bae4e2be689a5164081b0c8575b0e",
          "sha256": "fb77516145837f40cbc038be30f450b694ca468bf6453a8558fa5a33f423ad57",
          "sha1": "eebee5822cc48eece5f9a807a5f04bf0003ca429",
          "md5": "52cbc0af9795454b6be74b6848d36af7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crucible.ide_data-1.1.1-sources.jar",
          "url": "crucible.ide_data-1.1.1-sources.jar",
          "size": 2524,
          "sha512": "3a0cf26c8e9c92f7ec59a53726f7bc522fefbe43e835f7c02b1d3a35c8f4026b9ae007217adeff5693ef69519db9907e6217da9d3cddc41036d8498dc17ade99",
          "sha256": "1b2f7936eb8810d987c8e5b47fee596a6738b21220e22d73e84a4ebed5883c76",
          "sha1": "46ffe6c65e0a40f23fbae748e32fd04ab822f5c9",
          "md5": "965bd8dd5a59901b7f745a517fd05432"
        }
      ]
    }
  ]
}
