{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "data_util",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.1.jar",
          "url": "data_util-1.3.1.jar",
          "size": 221865,
          "sha512": "26cbf86ae37c795297720c7cf5034b3a011594df7664978ee1979fbfd46f417b0c38539c208bba0a497adbfae0e498d4f6d3106cc7d94bbfb112e0fc17c70a26",
          "sha256": "b88b2311dbe773c2022bb6a637fc7812744439fdb802cc9329c0f0cb20d35a28",
          "sha1": "b2c8d2e30fecd0e2fd36d4a8f779f32fc3659340",
          "md5": "4af9b720d36b15243e8e424e744cc878"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "data_util-1.3.1.jar",
          "url": "data_util-1.3.1.jar",
          "size": 221865,
          "sha512": "26cbf86ae37c795297720c7cf5034b3a011594df7664978ee1979fbfd46f417b0c38539c208bba0a497adbfae0e498d4f6d3106cc7d94bbfb112e0fc17c70a26",
          "sha256": "b88b2311dbe773c2022bb6a637fc7812744439fdb802cc9329c0f0cb20d35a28",
          "sha1": "b2c8d2e30fecd0e2fd36d4a8f779f32fc3659340",
          "md5": "4af9b720d36b15243e8e424e744cc878"
        }
      ]
    }
  ]
}
