{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.2.jar",
          "url": "asm_util-1.3.2.jar",
          "size": 121628,
          "sha512": "867e1fd5c542d779c033bb1098c00087148b7388ea361a277613019d4d62f0e33538d8a0f4c59fc4fbcba1a13074ab9874d605108bb194c67f1420af0a88bdeb",
          "sha256": "bcce25891db30aa2ca8e76238d4c191719871918414f20b2a534ce31f7943e2d",
          "sha1": "6ff9263c1185957951df709c99077d6908a3502f",
          "md5": "a56660ebea5a4040f50add1a9353de00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.2.jar",
          "url": "asm_util-1.3.2.jar",
          "size": 121628,
          "sha512": "867e1fd5c542d779c033bb1098c00087148b7388ea361a277613019d4d62f0e33538d8a0f4c59fc4fbcba1a13074ab9874d605108bb194c67f1420af0a88bdeb",
          "sha256": "bcce25891db30aa2ca8e76238d4c191719871918414f20b2a534ce31f7943e2d",
          "sha1": "6ff9263c1185957951df709c99077d6908a3502f",
          "md5": "a56660ebea5a4040f50add1a9353de00"
        }
      ]
    }
  ]
}
