{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.5.jar",
          "url": "asm_util-1.3.5.jar",
          "size": 128349,
          "sha512": "b01570f6d589c7167f6cf17db95999986fb95d1b32a42dd45ba0347562cc70bc75f273b8dbca8ac1797d1779927a52bc010e08817c1c96830c194ee1eace5cec",
          "sha256": "fb6f8e98a54e80e2edd8a0fd06f74bf04010576b9f3f25fc078884c6703dcb26",
          "sha1": "08bc0a79143c1ac1fd2e778216044486eb424c87",
          "md5": "b04452dd1b8876915ce498818b38e21d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.5.jar",
          "url": "asm_util-1.3.5.jar",
          "size": 128349,
          "sha512": "b01570f6d589c7167f6cf17db95999986fb95d1b32a42dd45ba0347562cc70bc75f273b8dbca8ac1797d1779927a52bc010e08817c1c96830c194ee1eace5cec",
          "sha256": "fb6f8e98a54e80e2edd8a0fd06f74bf04010576b9f3f25fc078884c6703dcb26",
          "sha1": "08bc0a79143c1ac1fd2e778216044486eb424c87",
          "md5": "b04452dd1b8876915ce498818b38e21d"
        }
      ]
    }
  ]
}
