{
  "formatVersion": "1.1",
  "component": {
    "group": "net.typho",
    "module": "asm_util",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.1.jar",
          "url": "asm_util-1.3.1.jar",
          "size": 121174,
          "sha512": "674846c0fec924a7461c58637a448f50d0b2ba89015b3227e4c47169bf584adcdd7b6498d61b6ecb7bb79df1a9ff1fadb02d5493f0de3df315a3e832b1db82d3",
          "sha256": "a1d99eb4a911371cec91dc7ae832bdb4a0210b9fed954a1cb73ca8ddbb0100bc",
          "sha1": "b089f560f5af5fbb74d7e3adb58efbf8de71581c",
          "md5": "763f9769b59156949bf9be54d08534ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_util-1.3.1.jar",
          "url": "asm_util-1.3.1.jar",
          "size": 121174,
          "sha512": "674846c0fec924a7461c58637a448f50d0b2ba89015b3227e4c47169bf584adcdd7b6498d61b6ecb7bb79df1a9ff1fadb02d5493f0de3df315a3e832b1db82d3",
          "sha256": "a1d99eb4a911371cec91dc7ae832bdb4a0210b9fed954a1cb73ca8ddbb0100bc",
          "sha1": "b089f560f5af5fbb74d7e3adb58efbf8de71581c",
          "md5": "763f9769b59156949bf9be54d08534ac"
        }
      ]
    }
  ]
}
